name: arrosage
description: Command mobile for arrosage
#
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1

  http: ^0.13.5



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/background.png


